### ISSUE TITLE
Version 1.0 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/ChowKick#15]
- [x] Testing:
  - [x] Ableton (Win64)
  - [x] Ableton (Win32)
  - [x] Reaper
  - [x] FL Studio
  - [x] Ableton (Mac)
  - [x] Logic Pro
  - [x] Garageband
  - [x] iOS (Standalone, AUM, GarageBand)
  - [x] Test installers
  - [x] Carla (Linux)
- [x] Update Docs:
  - [x] Create Changelog
  - [x] Update screenshots
  - [x] Create User Manual
  - [x] Update README
- [x] Create Release:
  - [x] Release to App Store
  - [x] Generate builds
  - [x] Tag a GitHub Release
- [x] Announce:
  - [x] Post on KVR
  - [x] Post on website
  - [x] Post on Patreon
  - [x] Post a demo video on YouTube...
