### ISSUE TITLE
Version 1.1.0 Release Checklist

### ISSUE THREAD

**Issue by jatinchowdhury18** [Chowdhury-DSP/ChowKick#33]
- [x] Test on Windows:
  - [x] Ableton
  - [x] FL Studio
  - [x] Reaper
  - [x] Studio One
- [x] Test on Mac:
  - [x] Ableton
  - [x] GarageBand
  - [x] Logic (M1)
  - [x] #34
- [x] Test on Linux: 
  - [x] Carla
  - [x] Ardour
- [x] Test on iOS:
  - [x] AUM
  - [x] GarageBand
  - [x] Standalone
- [x] Bump version number
- [x] Submit iOS build for review
- [x] Update CHANGELOG
- [x] Generate release builds/installers
- [x] Release iOS version
- [x] Tag GitHub Release
- [x] Update website
- [x] Postings:
  - [x] KVR
  - [x] AudioBus
  - [x] Webpage (news)
  - [x] Patreon

**Comment by porzione** [comment]
Hi, I'm playing with ChowKick.lv2 on Arch Linux with Reaper so I can test night builds, for now - ChowKick-Linux-x64-1.0.2.deb works fine in Arch

**Comment by jatinchowdhury18** [comment]
Awesome, thanks for helping with testing!
